main: io.nv.bukkit.CleanroomGenerator.CleanroomGenerator
name: ${project.artifactId}
version: ${project.version}
api-version: 1.13
website: ${plugin.website}
author: ${plugin.authors}
description: ${project.description}
load: STARTUP
